# Generated by Django 4.2 on 2024-05-01 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0014_stylist_availability_alter_admin_u_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('stylist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.stylist')),
            ],
        ),
    ]
