# Generated by Django 4.2 on 2024-05-22 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
        ('stylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.stylist'),
        ),
        migrations.AddField(
            model_name='stylistresponse',
            name='questionnaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.questionnaire'),
        ),
        migrations.AddField(
            model_name='stylistresponse',
            name='stylist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.stylist'),
        ),
        migrations.AddField(
            model_name='otp',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='style_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylist.style'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.stylist'),
        ),
    ]
