# Generated by Django 4.2 on 2024-04-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_remove_user_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('Stylist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.stylist')),
                ('questionnaire_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stylist.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='response_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stylist.response'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('national_id_front', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('national_id_back', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('good_conduct_cert', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('stylist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.stylist')),
            ],
        ),
    ]
