# Generated by Django 4.2 on 2024-05-22 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='StyleCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='StylistDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('national_id_front', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('national_id_back', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('good_conduct_cert', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('stylist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.stylist')),
            ],
        ),
        migrations.CreateModel(
            name='StyleVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('video', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('length', models.DecimalField(decimal_places=4, max_digits=12)),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylist.style')),
            ],
        ),
        migrations.AddField(
            model_name='style',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylist.stylecategorie'),
        ),
        migrations.AddField(
            model_name='style',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.stylist'),
        ),
    ]
