# Generated by Django 4.2 on 2024-04-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_img_url'),
        ('stylist', '0002_remove_questionnaire_response_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='UserResponse',
        ),
    ]
