# Generated by Django 4.2 on 2024-04-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0003_rename_response_userresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='Stylist_id',
            new_name='stylist_id',
        ),
    ]
