# Generated by Django 4.2 on 2024-04-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0005_booking_category_style_variation_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stylist',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='questionnaire_id',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='stylist_id',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
