# Generated by Django 4.2 on 2024-04-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_delete_otp'),
        ('stylist', '0006_remove_transaction_booking_remove_transaction_client_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='StyleCategorie',
        ),
        migrations.RenameModel(
            old_name='Variation',
            new_name='StyleVariation',
        ),
        migrations.RenameModel(
            old_name='Document',
            new_name='StylistDocument',
        ),
    ]
