# Generated by Django 4.2 on 2024-05-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0007_rename_category_stylecategorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylecategorie',
            old_name='name',
            new_name='category_name',
        ),
    ]
