# Generated by Django 4.2 on 2024-04-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_url',
            field=models.ImageField(blank=True, default='C:\\django\\stye_hub\\style_hub\\Media\\user_icon.jpeg', null=True, upload_to=''),
        ),
    ]
