# Generated by Django 4.2 on 2024-04-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('national_id_front', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('national_id_back', models.ImageField(blank=True, null=True, upload_to='Media/')),
                ('good_conduct_cert', models.ImageField(blank=True, null=True, upload_to='Media/')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='stylist',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Female', max_length=50),
        ),
        migrations.AddField(
            model_name='stylist',
            name='user_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
