# Generated by Django 4.2 on 2024-04-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_url',
        ),
    ]
