# Generated by Django 4.2 on 2024-04-24 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='client',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='stylist',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='stylist',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
