# Generated by Django 4.2 on 2024-05-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='avaiilability',
            field=models.BooleanField(default=False),
        ),
    ]
