# Generated by Django 4.2 on 2024-05-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_stylist_avaiilability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylist',
            old_name='avaiilability',
            new_name='availability',
        ),
    ]
