# Generated by Django 4.2 on 2024-05-01 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_admin_u_id_alter_client_u_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='availability',
        ),
        migrations.AlterField(
            model_name='admin',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
