# Generated by Django 4.2 on 2024-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_stylist_availability_alter_admin_u_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='u_id',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='u_id',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='u_id',
            field=models.UUIDField(editable=False),
        ),
    ]
